### ISSUE TITLE
Can we add Database name as a parameter

### ISSUE THREAD

**Issue by ameydhavle** [rjrudin/ml-migration-starter#1]
something like this 
DatabaseClient databaseClient = DatabaseClientFactory
                .newClient("demo.marklogic.com",
                        8000,
                        "risk-xml",
                        "admin",
                        "admin",
                        DatabaseClientFactory.Authentication.DIGEST);

**Comment by rjrudin** [comment]
See the commit - I added database and auth, and also added "help" as a task. Those things are already built into marklogic-spring-batch, which is convenient.

**Comment by RobertSzkutak** [comment]
Was support for this later taken out? Digging around the codebase it looks like the DatabaseClientFactory creation only takes host and port now.

https://github.com/rjrudin/ml-migration-starter/blob/master/src/main/java/org/example/MigrationConfig.java#L126

Also looks like auth was removed?

**Comment by rjrudin** [comment]
I don't recall, but those command line args may have been dropped when this was upgraded to use the latest version of marklogic-spring-batch. 

This is still intended to be a starter kit and not a solution for all scenarios. So for now, just clone and modify those lines of code that construct the DatabaseClient.
