### ISSUE TITLE
Is it possible to hook migration starter into an ingestion flow?

### ISSUE THREAD

**Issue by grtjn** [rjrudin/ml-migration-starter#19]
MLCP import can be attached to a flow by passing in a DHF transform, with a param pointing to an ingest flow. Can the same be down with migration starter? It is possible to set a transform on a DMSDK writer, but i am less sure about ml spring batch..

**Comment by rjrudin** [comment]
A key difference between MLCP and this project is that MLCP is an application, while the README for this project starts with "This is a starter kit for creating an application". Without this project, getting all the moving parts of Spring Batch in place can be difficult, which is why the README also states "The intent is to simplify the process of creating a migration application using Spring Batch". 

So the answer is "yes" because the audience for this project is a developer writing custom code, and thus the developer is free to do whatever they like. The simplest approach for this feature would be to configure the Writer to use the DHF REST transform that can reference an ingestion step (DHF 5) - or the equivalent transform for a DHF 4 ingestion flow.

**Comment by grtjn** [comment]
Thanks for the quick reply. I am aware of this being a starter kit project which is perfectly fine. I am merely looking for a line of code or two to get me going. There is sample code in the docs on how to use transforms with dmsdk, but is there an existing example for using transforms with ml spring batch too?

**Comment by rjrudin** [comment]
I'm almost certain that MarkLogicItemWriter has a setter for a ServerTransform:

https://github.com/rjrudin/ml-migration-starter/blob/master/src/main/java/org/example/MigrationConfig.java#L130

**Comment by grtjn** [comment]
It turns out there is a little more to it, so sharing this for posterity. marklogic-spring-batch has a DataHubItemWriter, but it seems out of date, so took a few bits out of that. In the end I added the following lines below L130 in MigrationConfig to make it kinda do what I was looking for:

```java
    // Configure writer for DHF use, if applicable
    if (flow != null && flow != "") {
      if (step == null || step == "") {
        step = "1";
      }
      String jobId = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX").format(new Date());

      Map<String,Object> map = new HashMap<>();
      Map<String,Object> headers = new HashMap<>();
      headers.put("jdbcDriver", jdbcDriver);
      headers.put("jdbcUrl", jdbcUrl);
      headers.put("jdbcUsername", jdbcUsername);
      headers.put("database", database);
      headers.put("table", table);
      map.put("headers",headers);
      String options = "{}";
      try {
        options = new ObjectMapper().writeValueAsString(map);
      } catch (Exception e) {
        System.out.println(e);
      }

      System.out.println("Using Data Hub Transform: " + flow + ", " + step +", " + jobId + ", " + options);
      ServerTransform serverTransform = new ServerTransform("mlRunIngest");
      serverTransform.addParameter("flow-name", flow);
      serverTransform.addParameter("step", step);
      serverTransform.addParameter("job-id", jobId);
      serverTransform.addParameter("options", options);
      writer.setServerTransform(serverTransform);
    }
```
and a few extra imports which required no extra dependencies in build.gradle:
```java
import java.util.Date;
import java.util.HashMap;
import java.text.SimpleDateFormat;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.marklogic.client.document.ServerTransform;
```

**Comment by grtjn** [comment]
I also exposed a few extra parameters, like `database`, `table`, `flow`, and `step`, all the way from gradle properties, build.gradle, Main.java into step callback of MigrationConfig...
